! needs to be added on each Layer3 interfaces for sampling
interface <interface_name>
    ip flow monitor <KENTIK-MONITOR-INPUT> sampler <KENTIK_NETFLOW_SAMPLER> input
    ip flow monitor <KENTIK-MONITOR-OUTPUT> sampler <KENTIK_NETFLOW_SAMPLER> output
    exit