! SNMP IOS-XR
!
feature sflow
!
! Set sample rate based on flow volume.
sflow sampling-rate {{device_sample_rate}}
! size of headers we intend to sample to catch multiple encapsulations
sflow max-sampled-size 200
! kentik ignores sflow counters so we can set this to zero
sflow counter-poll-interval 0
! maximum number of data bytes that can be sent in a single sample datagram. internet < 1500 bytes
sflow max-datagram-size 1400
!
! Kentik specific endpoints to receive sflow
sflow collector-ip {{kentik_ingest_ip_from_UI}}
sflow collector-port {{kentik_ingest_UDP_port_from_UI}}
!
! sFlow agent address to enable sFlow functionality on the device
! this can be any IP address configured on the device such as the loopback
sflow agent-ip {{ loopback-ip }}
! the IP address or source interface from which the device will source sflow packets from
sflow data-source interface {{ source-interface }}