policy-options {
    # Prefix List of Routes not to send to Kentik
    prefix-list KENTIK-NOSEND {
        0.0.0.0/0;
    }
    # Outbound policy for Kentik BGP session
    policy-statement KENTIK-OUT {
        term 5 {
            from {
                prefix-list KENTIK-NOSEND;
            }
            then reject;
        }
        then accept;
    }
}

protocols {
    bgp {
         # Group for the BGP session to Kentik
        group route-consumers_v4 {
            type internal;
            # Prevent short-lived reachability issues from triggering neighbor down events.
            hold-time 720;
            family inet {
                unicast;
            }
            family inet-vpn {
                unicast;
            }
            export KENTIK-OUT;
            # IP this RR should identify itself as in the cluster ID field
            cluster {{cluster_id}};
            # Kentik-provided peering IP.
            neighbor {{kentik_UI_bgp_peering_ipv4}} {
                description Kentik-Detect;
                # IP of local router interface or loopback.
                local-address {{local_interface_ip}};
                mtu-discovery;
            }
        }
    }
}

# IPv6 stuff follows.  Historically, it's been good to not try
# to be too clever with converged prefix lists, policy statements,
# etc so we build a parallel world for IPv6.
#
# NLRI information over foreign AF BGP sessions (i.e. IPv6 NLRI over a
# BGP session between IPv4 endpoints or vice-versa) is out of scope
# for this example, if indeed it's even supported by Kentik (didn't check).

policy-options {
    # Kentik doesn't want IPv6 default route either
    prefix-list KENTIK-NOSEND6 {
        0::0/0;
    }

    # so don't send the IPv6 default route
    policy-statement KENTIK-OUT6 {
	term 5 {
	    from {
		prefix-list KENTIK-NOSEND6;
	    }
	    then reject;
	}
	then accept;
    }
}


protocols {
    bgp {
        # Group for the IPv6 BGP session to Kentik
        group route-consumers_v6 {
	    type internal;
	    hold-time 720;
	    family inet6 {
		unicast;
	    }
	    family inet6-vpn {
		unicast;
	    }
	    export KENTIK-OUT6;
	    # note no cluster ID; it seems optional for the config to work
	    # and it's not as if we have to worry about route reflection loops
	    # when sending bgp info to Kentik anyway.
	    #
            # Kentik-provided peering IP.
 	    neighbor {{kentik_UI_bgp_peering_ipv6}} {
		description Kentik-Detect;
		# note this is an ipv6 address on your loopback interface
		# usual reachability concerns apply
		local-address {{local_interface_ip6}};
		mtu-discovery;
	    }
        }
    }
}

