# /etc/hsflowd.conf
# Host sFlow -> Kentik / kproxy / kflow collector

sflow {
  # Agent address: use the stable management/source IP of this host
  agent = {{device_sending_ip}}

  # Kentik collector, usually your local kproxy/kflow receiver
  collector {
    # The IP address of the Kentik collector. This is usually the IP of your kproxy/UA receiver.
    ip = {{ collector_ip }}
    # hsflowd defaults to 6343, but Kentik uses 9995 for kproxy/UA and 20013 for SaaS. 
    udpport = {{ collector_port | default: 6343 }}
  }

  # Counter polling interval in seconds
  # set to 0 to disable as Kentik ignores them.
  polling = 0
  # Sample rate 
  sampling = {{device_sample_rate}}
  #
  # You must define at leat one sample source. Pcap is the most common
  pcap { }

}